#define PNG_background 101
#define PNG_bendyBack 102
#define PNG_bendyBackShort 103
#define PNG_bendyCheckbox 104
#define PNG_bendyFull 105
#define PNG_bendyGuide 106
#define PNG_bendyInfoButton 107
#define PNG_bendyLessFull 108
#define PNG_bendyLetterB 109
#define PNG_bendyLetterD 110
#define PNG_bendyLetterE 111
#define PNG_bendyLetterN 112
#define PNG_bendyLetterY 113
#define PNG_bendyNumbers 114
#define PNG_bendySpinnerDown 115
#define PNG_bendySpinnerFrame 116
#define PNG_bendySpinnerUp 117
#define PNG_bendyTitle 118
#define PNG_biosFontCaseSensitive_gray_halfres 119
#define PNG_biosFontCaseSensitive_halfres 120
#define PNG_buttonContract 121
#define PNG_buttonExpand 122
#define PNG_checkboxPanning 123
#define PNG_checkboxPanningSimple 124
#define PNG_checkboxPitch 125
#define PNG_checkboxPitchSimple 126
#define PNG_checkboxTriggerNotes 127
#define PNG_checkboxTriggerNotesSimple 128
#define PNG_checkboxVelocity 129
#define PNG_checkboxVelocitySimple 130
#define PNG_harmonyFrame 131
#define PNG_knob 132
#define PNG_tinyCheckbox 133
#define PNG_tinyCheckboxSimple 134
# ifdef APSTUDIO_INVOKED
# ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
